name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]  # Test multiple Python versions

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]  # Install package in editable mode with test extras
    
    - name: Run tests
      run: |
        python -m unittest
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: success()  # Optional: Upload coverage to Codecov